=== prashant-baj/tradetrust/src/app/credentials/schema/LC.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "lcAmount","lcType","lcApplicant","currency","beneficiary","issuingBank","issuanceDate","expirationDate"
  ],
  "additionalProperties": false,
  "properties": {
    "lcNumber": {
      "type": "string"
    },
    "lcType": {
      "type": "string"
    },
    "lcApplicant": {
      "type": "string"
    },
    "lcAmount": {
      "type": "string"
    },
    "currency": {
      "type": "string"
    },
    "beneficiary": {
      "type": "string"
    },
    "issuingBank": {
      "type": "string"
    },
    "issuanceDate": {
      "type": "string"
    },
    "expirationDate": {
      "type": "string"
    },
    "terms": {
      "type": "array"
    }
  }
}

=== prashant-baj/tradetrust/src/app/credentials/config/data.json
{
    "lcNumber": "0a9s8dy0uas",
    "lcType": "Irrevocable",
    "lcApplicant": "United Imports Corporation",
    "lcAmount": "100",
    "currency": "USD",
    "beneficiary": "Acme Exports Corporation",
    "issuingBank": "JPMorgan London Branch",
    "issuanceDate": "2023-11-30",
    "expirationDate": "2024-01-30",
    "terms": [
        "Goods must be delivered",
        "LC must be verified digitally"
    ]
  }
